// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwzHjXaWUIjY--oMD9opzybSMR0xbArZ4',
    appId: '1:486810356673:android:6ed9ec04db442b6970fd40',
    messagingSenderId: '486810356673',
    projectId: 'basketball-a6472',
    storageBucket: 'basketball-a6472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcR-pQwfZ0qcPdaqK7ooL1qctJ52ZOWvU',
    appId: '1:486810356673:ios:2658fb8a8c15e7d970fd40',
    messagingSenderId: '486810356673',
    projectId: 'basketball-a6472',
    storageBucket: 'basketball-a6472.appspot.com',
    iosBundleId: 'com.example.basketballTraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIIjR7k4uRlQl6XDl_Lt9vOVXUoVhOTXA',
    appId: '1:486810356673:web:369261c019fcf8c170fd40',
    messagingSenderId: '486810356673',
    projectId: 'basketball-a6472',
    authDomain: 'basketball-a6472.firebaseapp.com',
    storageBucket: 'basketball-a6472.appspot.com',
    measurementId: 'G-PSRKMTG3GB',
  );
}
